const formatStatus = (status) => {
  if (!status) return "";

  return status
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

const formatHours = (minutes) => {
  if (!minutes) return "";

  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;

  if (hours === 0) return `${mins} mins`;

  return `${hours}h ${mins}m`;
};

const getPeriodLabel = (dateFilter) => {
  if (dateFilter === "today") return "Today";
  if (dateFilter === "week") return "This Week";
  if (dateFilter === "month") return "This Month";
  return "All Records";
};

const printAttendance = (attendances, dateFilter) => {
  const periodLabel = getPeriodLabel(dateFilter);

  const rows = attendances
    .map(
      (attendance) => `
        <tr>
          <td>${attendance.employee?.employeeNo ?? ""}</td>
          <td>${attendance.employee?.firstName ?? ""} ${
            attendance.employee?.lastName ?? ""
          }</td>
          <td>${attendance.employee?.department?.name ?? ""}</td>
          <td>${new Date(attendance.date).toLocaleDateString("en-PH")}</td>
          <td>${
            attendance.timeIn
              ? new Date(attendance.timeIn).toLocaleTimeString("en-PH")
              : ""
          }</td>
          <td>${
            attendance.timeOut
              ? new Date(attendance.timeOut).toLocaleTimeString("en-PH")
              : ""
          }</td>
          <td>${
            attendance.lateMinutes
              ? `${attendance.lateMinutes} mins`
              : "On Time"
          }</td>
          <td>${formatHours(attendance.workingHours)}</td>
          <td>${formatStatus(attendance.status)}</td>
          <td>${attendance.remarks ?? ""}</td>
        </tr>
      `
    )
    .join("");

  const printWindow = window.open("", "_blank");

  printWindow.document.write(`
    <html>
      <head>
        <title>Attendance Report - ${periodLabel}</title>

        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 24px;
            color: #0f172a;
          }

          h1 {
            margin: 0;
            font-size: 22px;
          }

          h2 {
            margin: 6px 0 18px;
            font-size: 16px;
            color: #334155;
          }

          .meta {
            margin-bottom: 22px;
            font-size: 13px;
            color: #475569;
          }

          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
          }

          th {
            background: #2563eb;
            color: white;
            padding: 9px;
            text-align: left;
          }

          td {
            padding: 8px;
            border-bottom: 1px solid #e5e7eb;
          }

          tr:nth-child(even) {
            background: #f8fafc;
          }

          .footer {
            margin-top: 28px;
            font-size: 11px;
            color: #64748b;
          }

          @media print {
            body {
              padding: 12px;
            }
          }
        </style>
      </head>

      <body>
        <h1>SCRIPTHEX ENTERPRISE SUITE</h1>
        <h2>Attendance Report</h2>

        <div class="meta">
          <div><strong>Report Period:</strong> ${periodLabel}</div>
          <div><strong>Date Generated:</strong> ${new Date().toLocaleString(
            "en-PH"
          )}</div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Employee No</th>
              <th>Employee</th>
              <th>Department</th>
              <th>Date</th>
              <th>Time In</th>
              <th>Time Out</th>
              <th>Late</th>
              <th>Hours</th>
              <th>Status</th>
              <th>Remarks</th>
            </tr>
          </thead>

          <tbody>
            ${rows || `<tr><td colspan="10">No attendance records found.</td></tr>`}
          </tbody>
        </table>

        <div class="footer">
          Generated by ScriptHex Enterprise Suite
        </div>

        <script>
          window.onload = function () {
            window.print();
          };
        </script>
      </body>
    </html>
  `);

  printWindow.document.close();
};
export default printAttendance;
