-- AlterTable
ALTER TABLE `employee` ADD COLUMN `civilStatus` VARCHAR(191) NULL,
    ADD COLUMN `emergencyContactName` VARCHAR(191) NULL,
    ADD COLUMN `emergencyContactPhone` VARCHAR(191) NULL,
    ADD COLUMN `employmentType` ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'PROBATIONARY') NOT NULL DEFAULT 'FULL_TIME',
    ADD COLUMN `nationality` VARCHAR(191) NULL,
    ADD COLUMN `photo` VARCHAR(191) NULL,
    ADD COLUMN `qrCode` VARCHAR(191) NULL,
    ADD COLUMN `rfidCard` VARCHAR(191) NULL,
    ADD COLUMN `salary` DECIMAL(10, 2) NULL,
    ADD COLUMN `suffix` VARCHAR(191) NULL,
    MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'RESIGNED', 'TERMINATED') NOT NULL DEFAULT 'ACTIVE';
