import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const formatStatus = (status) => {
  if (!status) return "";

  return status
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

const formatHours = (minutes) => {
  if (!minutes) return "";

  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;

  if (hours === 0) return `${mins} mins`;

  return `${hours}h ${mins}m`;
};

const getPeriodLabel = (dateFilter) => {
  if (dateFilter === "today") return "Today";
  if (dateFilter === "week") return "This Week";
  if (dateFilter === "month") return "This Month";
  return "All Records";
};

export const exportAttendancePDF = (attendances, dateFilter) => {
  const periodLabel = getPeriodLabel(dateFilter);

  const doc = new jsPDF("landscape", "mm", "a4");

  doc.setFontSize(16);
  doc.text("SCRIPTHEX ENTERPRISE SUITE", 14, 16);

  doc.setFontSize(12);
  doc.text("Attendance Report", 14, 24);

  doc.setFontSize(9);
  doc.text(`Report Period: ${periodLabel}`, 14, 31);
  doc.text(`Date Generated: ${new Date().toLocaleString("en-PH")}`, 14, 37);

  autoTable(doc, {
    startY: 45,
    head: [
      [
        "Employee No",
        "Employee",
        "Department",
        "Date",
        "Time In",
        "Time Out",
        "Late",
        "Working Hours",
        "Status",
        "Remarks",
      ],
    ],
    body: attendances.map((attendance) => [
      attendance.employee?.employeeNo ?? "",
      `${attendance.employee?.firstName ?? ""} ${
        attendance.employee?.lastName ?? ""
      }`.trim(),
      attendance.employee?.department?.name ?? "",
      new Date(attendance.date).toLocaleDateString("en-PH"),
      attendance.timeIn
        ? new Date(attendance.timeIn).toLocaleTimeString("en-PH")
        : "",
      attendance.timeOut
        ? new Date(attendance.timeOut).toLocaleTimeString("en-PH")
        : "",
      attendance.lateMinutes ? `${attendance.lateMinutes} mins` : "On Time",
      formatHours(attendance.workingHours),
      formatStatus(attendance.status),
      attendance.remarks ?? "",
    ]),
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  const pageCount = doc.internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Generated by ScriptHex Enterprise Suite | Page ${i} of ${pageCount}`,
      14,
      200
    );
  }

  doc.save(`Attendance Report - ${periodLabel}.pdf`);
};
